
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module pcihello(

	//////////// CLOCK //////////
	CLOCK_50, 	// BANK 4
	CLOCK2_50, 	// BANK 7
	CLOCK3_50, 	// BANK 3A

	//////////// LED (High Active) //////////
	LEDG,
	LEDR,

	//////////// KEY (Active Low) //////////
	KEY,
	
	//////////// LCD //////////
	LCD_DATA,
	LCD_RW,
	LCD_EN,
	LCD_RS,
	LCD_ON,
	
	// switches
   SW,
	
	//////////// SEG7 (Low Active) //////////
	HEX0,
	HEX1,
	HEX2,
	HEX3,
	HEX4,
	HEX5,
	HEX6,
	HEX7,

	//////////// PCIe //////////
	PCIE_PERST_N,
	PCIE_REFCLK_P,
	PCIE_RX_P,
	PCIE_TX_P,
	PCIE_WAKE_N,

	//////////// Fan Control //////////
	FAN_CTRL 
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		CLOCK_50;
input 		          		CLOCK2_50;
input 		          		CLOCK3_50;

//////////// LED (High Active) //////////
output		     [8:0]		LEDG;
output		    [17:0]		LEDR;

//////////// KEY (Active Low) //////////
input 		     [3:0]		KEY;
input            [17:0]	   SW;

//////////// LCD //////////
output		     [7:0]		LCD_DATA;
output		     				LCD_RW;
output		     				LCD_EN;
output		     				LCD_RS;
output		     				LCD_ON;

//////////// SEG7 (Low Active) //////////
output		     [6:0]		HEX0;
output		     [6:0]		HEX1;
output		     [6:0]		HEX2;
output		     [6:0]		HEX3;
output		     [6:0]		HEX4;
output		     [6:0]		HEX5;
output		     [6:0]		HEX6;
output		     [6:0]		HEX7;

//////////// PCIe //////////
input 		          		PCIE_PERST_N;
input 		          		PCIE_REFCLK_P;
input 		     [1:0]		PCIE_RX_P;
output		     [1:0]		PCIE_TX_P;
output		          		PCIE_WAKE_N;

//////////// Fan Control //////////
inout 		          		FAN_CTRL;


//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [31:0] hex1234;
wire [31:0] hex5678;
wire [31:0] ledverm;
wire [31:0] ledverd;
wire [31:0] lcd;
wire [31:0] switches;
wire [31:0] buttons;


//=======================================================
//  Structural coding
//=======================================================

    pcihellocore u0 (
        .pcie_hard_ip_0_rx_in_rx_datain_0       (PCIE_RX_P[0]),       //     pcie_hard_ip_0_rx_in.rx_datain_0
        .pcie_hard_ip_0_tx_out_tx_dataout_0     (PCIE_TX_P[0]),     //    pcie_hard_ip_0_tx_out.tx_dataout_0
        .pcie_hard_ip_0_powerdown_pll_powerdown (PCIE_WAKE_N), 		// pcie_hard_ip_0_powerdown.pll_powerdown
        .pcie_hard_ip_0_powerdown_gxb_powerdown (PCIE_WAKE_N), //                         .gxb_powerdown
        .pcie_hard_ip_0_refclk_export           (PCIE_REFCLK_P),           //    pcie_hard_ip_0_refclk.export
        .pcie_hard_ip_0_pcie_rstn_export        (PCIE_PERST_N),
        .hex1234_external_connection_export     (hex1234),     // hex1234_external_connection.export
        .hex5678_external_connection_export     (hex5678),     // hex5678_external_connection.export
        .ledverm_external_connection_export     (ledverm),     // ledverm_external_connection.export
        .ledverd_external_connection_export     (ledverd),     // ledverd_external_connection.export
        .lcd_external_connection_export     (lcd),     // lcd_external_connection.export
        .switches_external_connection_export     (switches),     // switches_external_connection.export
        .buttons_external_connection_export     (buttons),     // buttons_external_connection.export
	  );

	//////////// HEX 0-3 //////////
assign HEX0 = hex1234[ 6: 0];
assign HEX1 = hex1234[14: 8];
assign HEX2 = hex1234[22:16];
assign HEX3 = hex1234[30:24];

	//////////// HEX 4-7 //////////
assign HEX4 = hex5678[ 6: 0];
assign HEX5 = hex5678[14: 8];
assign HEX6 = hex5678[22:16];
assign HEX7 = hex5678[30:24];

	//////////// LEDs Vermelhos //////////
//assign LEDR = ledverm[17: 0];
assign LEDR = SW[17:0];

	//////////// LEDs Verdes //////////
//assign LEDG = ledverd[8: 0];
assign LEDG[3:0] = KEY[3:0];
assign LEDG[8:4] = ledverd[8: 4];

	//////////// LCD //////////
assign LCD_DATA = lcd[ 7: 0];
assign LCD_RW = lcd[8];
assign LCD_EN = lcd[9];
assign LCD_RS = lcd[10];
assign LCD_ON = lcd[11];

	//////////// Switches //////////
//assign switches = SW[17:0];

	//////////// Botões //////////
//assign buttons = KEY[3:0];

	//////////// FAN Control //////////
assign FAN_CTRL = 1'b1;

endmodule
